# Generated by Django 4.2.2 on 2023-07-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name": "video", "verbose_name_plural": "videos"},
        ),
        migrations.RemoveField(model_name="video", name="video_url",),
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.FileField(default="default_video.mp4", upload_to="videos/"),
        ),
    ]
