# Generated by Django 4.2.2 on 2023-07-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_alter_video_options_remove_video_video_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
